In [8]:
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
df = pd.read_csv("sf_edge_pos.csv")
display(df)

            start_x      start_y        end_x        end_y
0       1905.934692  2760.598145  1878.359985  2731.011475
1       1905.934692  2760.598145  1915.310181  2764.824951
2       1905.934692  2760.598145  1910.898193  2758.484863
3       4526.182617  3337.534180  4520.116211  3329.080811
4       4526.182617  3337.534180  4519.013184  3337.534180
...             ...          ...          ...          ...
222996  5798.537598  7734.572266  5795.780273  7731.050293
222997  5801.294922  7738.094727  5798.537598  7734.572266
222998  3826.947266  2445.970703  3824.068604  2441.159180
222999  5139.633301  6892.003418  5139.131348  6891.918457
223000  5164.417480  6922.921387  5165.293945  6924.055664

[223001 rows x 4 columns]

In [ ]:
for index, row in df.iterrows():
    plt.plot([row['start_x'], row['end_x']], [row['start_y'], row['end_y']])

plt.xlabel('X')
plt.ylabel('Y')
plt.title('Lines from DataFrame')
plt.grid(True)
plt.show()

In [ ]:
node_dist = pd.read_csv('node_distances.csv')
plt.figure(figsize=(8, 5))  # Set the figure size
cmap = 'viridis'

# Plot the scatter plot with color grading based on distance values
scatter = plt.scatter(node_dist['node_x'], node_dist['node_y'], c=node_dist['average_distance'], cmap=cmap, s=100, alpha=0.8, label='Scatter Plot')
plt.colorbar(scatter, label='Distances')

plt.show()

In [ ]:
#Graph of Dijkstra's weighted shortest distances
node_dist = pd.read_csv('node_weighted_distances.csv')
plt.figure(figsize=(8, 5))  # Set the figure size
cmap = 'viridis'

# Plot the scatter plot with color grading based on distance values
scatter = plt.scatter(node_dist['node_x'], node_dist['node_y'], c=node_dist['average_distance'], cmap=cmap, s=100, alpha=0.8, label='Scatter Plot')
plt.colorbar(scatter, label='Weights')

plt.show()